import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import 'antd/dist/reset.css';
import "./globals.css";

import Navbar from "@/Component/Navbar/Navbar";
import RootLayoutWrapper from "@/Component/Layout/RootLayoutWrapper";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
   display: 'swap', 
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // You can add as many as you need
  variable: "--font-roboto",
   display: 'swap', 
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
   display: 'swap', 
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
   display: 'swap', 
  
});

export const metadata: Metadata = {
  title: "Job Finding App",
  description: "Generated by MH Parvez",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${poppins.variable} antialiased`}>
        <AntdRegistry>
          <RootLayoutWrapper>{children}</RootLayoutWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
